# Generated by Django 5.1.2 on 2025-01-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_illustration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
    ]
