# Generated by Django 5.1.2 on 2025-01-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_owner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
