# Generated by Django 5.1.2 on 2025-01-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.skill')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tag')),
            ],
        ),
    ]
